name: Build Docker Image for Tag 1.0.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag 1.0.8
        uses: actions/checkout@v4
        with:
          ref: '1.0.8' # 指定检出 1.0.8 的 tag

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        env:
          IMAGE_NAME: gvstarsky/betterforward # 替换为你的 Docker 镜像名称
        run: |
          docker build -t $IMAGE_NAME:1.0.8 .
          docker push $IMAGE_NAME:1.0.8

